name: Nuke
on:
  # schedule:
  #   - cron: '0 10 * * 0'
  push:
    branches:
      - main
  #   types: [ opened, edited, reopened, synchronize ]
    # paths:
    #   - 'scripts/**'
    #   - '.github/workflows/tools-nuke.yaml'
  # workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  NUKE_ACCOUNT_IDS: ${{ secrets.NUKE_ACCOUNT_IDS }}
  # NUKE_SKIP_ENVIRONMENTS: ${{ secrets.NUKE_SKIP_ENVIRONMENTS }}
  # TF_IN_AUTOMATION: true
defaults:
  run:
    shell: bash

jobs:

  nuke:
    name: Nuke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install AWS Nuke
        run: |
          echo "BEGIN: Install AWS Nuke"
          mkdir -p $HOME/bin
          wget -c "https://github.com/rebuy-de/aws-nuke/releases/download/${AWS_NUKE_VERSION}/aws-nuke-${AWS_NUKE_VERSION}-linux-amd64.tar.gz" -O - | tar -xz -C $HOME/bin
          mv "$HOME/bin/aws-nuke-${AWS_NUKE_VERSION}-linux-amd64" $HOME/bin/aws-nuke
          chmod +x $HOME/bin/aws-nuke
          echo "END: Install AWS Nuke"
        env:
          AWS_NUKE_VERSION: v2.16.0
      - name: Nuke
        run: |
          echo "BEGIN: Nuke"
          bash scripts/nuke.sh
          echo "END: Nuke"
